### ISSUE TITLE
rviz: execute selected solution uses unactuated joints

### ISSUE THREAD

**Issue by LeroyR** [ubi-agni/moveit_task_constructor#14] opened 2019-05-23 12:46 UTC
The rviz execute button tries to actuate all joints. Task.execute(solution) uses the correct joints.

e.x.:

ERROR [ros.moveit_task_constructor_capabilities.ExecuteTaskSolution]: Could not find JointModelGroup that actuates {caster_back_left_1_joint, caster_back_left_2_joint, caster_back_right_1_joint, caster_back_right_2_joint, caster_front_left_1_joint, caster_front_left_2_joint, caster_front_right_1_joint, caster_front_right_2_joint, suspension_left_joint, wheel_left_joint, suspension_right_joint, wheel_right_joint, torso_lift_joint, arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint, gripper_finger_joint, head_1_joint, head_2_joint}

**Comment by yepw** [comment] 2019-07-09 16:28
Hi, I am having the same issue. Did you figure it out?

**Comment by rhaschke** [comment] 2019-07-11 13:37
Duplicate of https://github.com/ros-planning/moveit_task_constructor/issues/93. See for workaround there.

**Closed as completed by rhaschke** 2019-07-11 13:37 UTC
